# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: Generate OpenAPI in Repositories

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

concurrency:
  group: openapi-repositories-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  openapi-repositories:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ "8.1" ]
        repositories:
          - "nextcloud/assistant"
          - "nextcloud/notifications"
          - "nextcloud/server"
          - "nextcloud/spreed"
          - "nextcloud/tables"

    name: openapi-repositories

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository for testing
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: ${{ matrix.repositories }}
          path: temp-repository

      - name: Install dependencies
        run: composer i

      - name: Generate OpenAPI
        if: matrix.repositories != 'nextcloud/server'
        working-directory: temp-repository/
        run: ../generate-spec

      - name: Generate OpenAPI - Server
        if: matrix.repositories == 'nextcloud/server'
        working-directory: temp-repository/
        run: |
          for path in core apps/*; do
            if [ ! -f "$path/.noopenapi" ]; then
              ../generate-spec "$path" "$path/openapi.json" || exit 1
            fi
          done

      - name: Show changes of the API for assistance
        working-directory: temp-repository/
        run: |
            git status
            git --no-pager diff

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: openapi-repositories

    if: always()

    name: openapi-repositories-summary

    steps:
      - name: Summary status
        run: if ${{ needs.openapi-repositories.result != 'success' && needs.openapi-repositories.result != 'skipped' }}; then exit 1; fi
